  #  mkdir /root/4.10.26; cd /root/4.10.26
  #  wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.10.26/openshift-client-linux.tar.gz 
  #  wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.10.26/openshift-install-linux.tar.gz
  #  ln -s /root/4.10.26/kubectl /usr/local/bin/kubectl
  #  ln -s /root/4.10.26/oc /usr/local/bin/oc
  #  ln -s /root/4.10.26/openshift-install /usr/local/bin//openshift-install


---
- hosts: infra
  gather_facts: true
  vars_files: vars/vmw_env.yml
  vars:
    - ocp_maj: 4.6
    - mirror: "https://mirror.openshift.com/pub/openshift-v4"
    - baseurl: "{{ mirror }}/dependencies/rhcos/{{ ocp_maj }}/{{ rhcos_ver }}"
    - client_mirror: "https://mirror.openshift.com/pub/openshift-v4/clients"
    
  become: no
  serial: 4
  tasks: 


# Create folder and download images into httpd

    - name: Create a ignitions directory if it does not exist
      file:
        path: "/var/www/html/openshift4/{{ rhcos_ver }}/ignitions"
        state: directory
        mode: '0755'

    - name: Create a RHCOS images directory if it does not exist
      file:
        path: /var/www/html/openshift4/images
        state: directory
        mode: '0755'

    - name: Download rhcos-4.6.1-x86_64-live-rootfs.x86_64.img to /root folder
      get_url:
        url: "{{ baseurl }}/rhcos-{{ rhcos_ver }}-x86_64-live-rootfs.x86_64.img"
        dest: "/var/www/html/openshift4/images/rhcos-{{ rhcos_ver }}-x86_64-live-rootfs.x86_64.img"
        force: no
        mode: 0644
      
    - name: Download rhcos-4.6.1-x86_64-live-kernel-x86_64 to /root folder
      get_url:
        url: "{{ baseurl }}/rhcos-{{ rhcos_ver }}-x86_64-live-kernel-x86_64"
        dest: /var/www/html/openshift4/images/rhcos-4.6.1-x86_64-live-kernel-x86_64
        force: no
        mode: 0644

    - name: Download rhcos-4.6.1-x86_64-live-initramfs.x86_64.img to /root folder
      get_url:
        url: "{{ baseurl }}/rhcos-{{ rhcos_ver }}-x86_64-live-initramfs.x86_64.img"
        dest: /var/www/html/openshift4/images/rhcos-4.6.1-x86_64-live-initramfs.x86_64.img
        force: no
        mode: 0644
        

# Configure syslinux

    - name: Install syslinux service
      yum:
        name: syslinux
        state: present
        
# Download openshift-install and oc, kubectl binaries from the OpenShift clients mirror into /root/<version>/ then create shortocut links in /usr/local/bin 

    - name: Download oc to /root folder
      get_url:
        url: "{{ client_mirror }}/ocp/{{ rhcos_ver }}/openshift-client-linux-{{ rhcos_ver }}.tar.gz"
        dest: "/root/{{ rhcos_ver }}/openshift-client-linux-{{ rhcos_ver }}.tar.gz"
        force: no
        mode: 0644

    - name: Download openshift-install to /root folder
      get_url:
        url: "{{ client_mirror }}/ocp/{{ rhcos_ver }}/openshift-install-linux.tar.gz"
        dest: "/root/{{ rhcos_ver }}/openshift-install-linux.tar.gz"
        force: no
        mode: 0644

    - name: Check openshift-client is exists  
      stat:
        path: "/root/{{ rhcos_ver }}/oc"
      register: ocl

    - name: Check openshift-install-linux is exists  
      stat:
        path: "/root/{{ rhcos_ver }}/openshift-install-linux"
      register: oil
      
    - name: Extract /root/openshift-install-linux.tar.gz
      ansible.builtin.unarchive:
        src:  "/root/{{ rhcos_ver }}/openshift-install-linux.tar.gz"
        dest: "/root/{{ rhcos_ver }}"
        mode: 0755
        remote_src: yes
      when: not oil.stat.exists

    - name: Extract /root/openshift-client-linux-4.6.1.tar.gz
      ansible.builtin.unarchive:
        src: /root/{{ rhcos_ver }}/openshift-client-linux-{{ rhcos_ver }}.tar.gz
        dest: /root/{{ rhcos_ver }}/
        mode: 0755
        remote_src: yes
      when: not ocl.stat.exists

    - name: Create a /etc/bash_completion.d/ directory if it does not exist
      file:
        path: /etc/bash_completion.d/
        state: directory
        mode: '0755'

    - name: Set up the bash commands completion
      shell: |
        oc completion bash > /etc/bash_completion.d/openshift 
        openshift-install completion bash > /etc/bash_completion.d/openshift-install
        source /etc/bash_completion.d/openshift
        source /etc/bash_completion.d/openshift-install
      args:
        executable: /bin/bash

   