---
- hosts: infra
  gather_facts: true
  vars:
    - my_pull_secret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2toYW5oY2h1MWVmdGlvb2N1Z2JtajM2eGZ1ZnllbGxueW54OkwzSVZOUzE4UE1KOTExVFk3WkhVNlRVT0xOSlZWRkxRUEJUS00yUVYzSTU1R0hCNDVGQTdBME84UVpMVVE2NjE=","email":"khanh.chu@svtech.com.vn"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2toYW5oY2h1MWVmdGlvb2N1Z2JtajM2eGZ1ZnllbGxueW54OkwzSVZOUzE4UE1KOTExVFk3WkhVNlRVT0xOSlZWRkxRUEJUS00yUVYzSTU1R0hCNDVGQTdBME84UVpMVVE2NjE=","email":"khanh.chu@svtech.com.vn"},"registry.connect.redhat.com":{"auth":"NzU4MTE5Mnx1aGMtMWVmVGlPT0NVZ2JNSjM2WGZVZnlFTGxOWW54OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJNE9ESmxZekU0T0dRNE5HTTBNbVZsWWpGbFl6ZzRZalJqTnpNMk1HWTBaU0o5LmhnVFRBYzJJNjZFLVVLWkl4RnFqNm1scklhNXI3WDJFZ2VscUhHMVJ1QTc0RDFZZHBWeGxnZzF3ckE5YTJJZHVnV3VKWElJeTNUUmpPVnF6WTJGUEcxdHl0bDhNcUFMWlpMUDBob2dYUDEzdmVpZmFhRWdqU3JqekFDT29VOGNTV2FKV01XRVk4cm4ydkJxOUsyeXlmb0VqVUgyZDdrc0xMN0tmOUR5QkhyRk9RZDgwZnB1MzJFSVVYcEtVWlBucjY0N3BEaXFNUFNkNnZwZ1BnNjROdTZjVEdvZmdZTnl0dS1kUF9DaEc5cFl4NUpYV2g0cG1wVFZjbjRWRXlVdDRKYlhfNUFwUUF2anRJQVA5Rkd6VThFanZVMFREbDFQYnF3OWVkaGUydE83MGpxejJDRjBEWVpaaXU2S0VJa2R4VjF6Rm1hYkljckpEeTFudTg2TFpudnpfQU0zNUQ4TVl0ai0yT3FUS2R6US1qektEUENCeGlQTWpZNC1sRGQxM1owRWFqYlZsckNkamQ2NklUMEZaUGdYQ1FQMlcwRnd1T0w3T0ROaGJVRWhhR2pRbFBId2psd0dqRnRMWS1oZHkxYnlNRVFUNzhHSExLeW5wWDI2Y1MzODNuaVZVOGJPZURTT0JiRVotbEhDeVhzazg4M2FsbWh3cjBiMndSZEVtVkxNUkpxYnd4b05GWXpVVU9hWVEzX0JJSDZ0STYxU3BYc2FCckgtOUdkbnUwU1JlcmJMNGlJTmFXVlRFM2hjZERtb0JoS2s1QjJVd1lNU0d1d0gzRnRrNWlfMGlNM2UwaUpWd3pqdHBqWDBJYS1DSDU4TG9LbXc1MnZaNHMweVN5U3FRV2pOeFZpYmpzNlJ6eUYzdXAza3BMbVlqMnE3WUJGeTFCS004anpV","email":"khanh.chu@svtech.com.vn"},"registry.redhat.io":{"auth":"NzU4MTE5Mnx1aGMtMWVmVGlPT0NVZ2JNSjM2WGZVZnlFTGxOWW54OmV5SmhiR2NpT2lKU1V6VXhNaUo5LmV5SnpkV0lpT2lJNE9ESmxZekU0T0dRNE5HTTBNbVZsWWpGbFl6ZzRZalJqTnpNMk1HWTBaU0o5LmhnVFRBYzJJNjZFLVVLWkl4RnFqNm1scklhNXI3WDJFZ2VscUhHMVJ1QTc0RDFZZHBWeGxnZzF3ckE5YTJJZHVnV3VKWElJeTNUUmpPVnF6WTJGUEcxdHl0bDhNcUFMWlpMUDBob2dYUDEzdmVpZmFhRWdqU3JqekFDT29VOGNTV2FKV01XRVk4cm4ydkJxOUsyeXlmb0VqVUgyZDdrc0xMN0tmOUR5QkhyRk9RZDgwZnB1MzJFSVVYcEtVWlBucjY0N3BEaXFNUFNkNnZwZ1BnNjROdTZjVEdvZmdZTnl0dS1kUF9DaEc5cFl4NUpYV2g0cG1wVFZjbjRWRXlVdDRKYlhfNUFwUUF2anRJQVA5Rkd6VThFanZVMFREbDFQYnF3OWVkaGUydE83MGpxejJDRjBEWVpaaXU2S0VJa2R4VjF6Rm1hYkljckpEeTFudTg2TFpudnpfQU0zNUQ4TVl0ai0yT3FUS2R6US1qektEUENCeGlQTWpZNC1sRGQxM1owRWFqYlZsckNkamQ2NklUMEZaUGdYQ1FQMlcwRnd1T0w3T0ROaGJVRWhhR2pRbFBId2psd0dqRnRMWS1oZHkxYnlNRVFUNzhHSExLeW5wWDI2Y1MzODNuaVZVOGJPZURTT0JiRVotbEhDeVhzazg4M2FsbWh3cjBiMndSZEVtVkxNUkpxYnd4b05GWXpVVU9hWVEzX0JJSDZ0STYxU3BYc2FCckgtOUdkbnUwU1JlcmJMNGlJTmFXVlRFM2hjZERtb0JoS2s1QjJVd1lNU0d1d0gzRnRrNWlfMGlNM2UwaUpWd3pqdHBqWDBJYS1DSDU4TG9LbXc1MnZaNHMweVN5U3FRV2pOeFZpYmpzNlJ6eUYzdXAza3BMbVlqMnE3WUJGeTFCS004anpV","email":"khanh.chu@svtech.com.vn"}}}'
  become: no
  serial: 4
  tasks: 

    - name: Create ocp4upi directory
      file: 
        path: "/root/ocp4upi/{{rhcos_ver}}"
        recurse: yes
        state: directory
        
    - name: Copy file install-config.yaml
      copy:
        src: config/ocp4upi/install-config.yaml
        dest: "/root/ocp4upi/{{rhcos_ver}}/install-config.yaml"

    - name: Copy pull_secret into file install-config.yaml
      lineinfile:
        line: "pullSecret: '{{ my_pull_secret }}'"
        regexp: ^pullSecret 
        path: "/root/ocp4upi/{{rhcos_ver}}/install-config.yaml"
  
    - name: Create ocp4upi directory
      file: 
        path: "/root/.ssh/{{rhcos_ver}}"
        recurse: yes
        state: directory

    - name: Create a keypair
      community.crypto.openssh_keypair:
        path: "/root/.ssh/{{rhcos_ver}}/id_rsa"    
        force: True
      register: output_keypair

    - name: Copy public key into file install-config.yaml
      lineinfile:
        line: "sshKey: {{ output_keypair.public_key }}"
        regexp: ^sshKey
        path: "/root/ocp4upi/{{rhcos_ver}}/install-config.yaml"

    - name: Create manifest
      shell:
        openshift-install create manifests --dir="/root/ocp4upi/{{rhcos_ver}}"

    - name: Create ignition
      shell:
        openshift-install create ignition-configs --dir="/root/ocp4upi/{{rhcos_ver}}"

    - name: Copy file bootstrap.ign
      copy:
        remote_src: true
        src: "/root/ocp4upi/{{rhcos_ver}}/bootstrap.ign"
        dest: "/var/www/html/openshift4/{{rhcos_ver}}/ignitions/bootstrap.ign"

    - name: Copy file bootstrap.ign
      copy:
        remote_src: true
        src: "/root/ocp4upi/{{rhcos_ver}}/master.ign"
        dest: "/var/www/html/openshift4/{{rhcos_ver}}/ignitions/master.ign"

    - name: Copy file metadata.json
      copy:
        remote_src: true
        src: "/root/ocp4upi/{{rhcos_ver}}/metadata.json"
        dest: "/var/www/html/openshift4/{{rhcos_ver}}/ignitions/metadata.json"

    - name: Copy file worker.ign
      copy:
        remote_src: true
        src: "/root/ocp4upi/{{rhcos_ver}}/worker.ign"
        dest: "/var/www/html/openshift4/{{rhcos_ver}}/ignitions/worker.ign"      
