---
- hosts: utility
  gather_facts: true
  become: true
  serial: 4
  tasks: 

    - name: set system hostname
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Copy host file to etc host
      copy:
        src: config/etc/hosts
        dest: /etc/hosts
    
    - name: Create a backup directory if it does not exist
      file:
        path: /etc/yum.repos.d/old
        state: directory
        mode: '0755'
    
    - name: Move all repo files to backup directory
      shell: mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/old
      ignore_errors: yes
    
    - name: Copy repo file to etc host
      copy:
        src: config/etc/yum.repos.d/2022_07.repo
        dest: /etc/yum.repos.d/
 
