---
- hosts: localhost
  vars_files: vars/vmw_env.yml
  gather_facts: no
  become: true
  serial: 4
  tasks:     
    - name: Deploy the cluster on VMware environment
      include: deploy_vmware_cluster.yml
      when: action == "create"

    - name: Destroy the cluster on VMware environment
      include: destroy_vmware_cluster.yml
      when: action == "destroy"